[package]
name = "test-nostd"
version = "0.1.0"
authors = ["Gianmarco Garrisi <gianmarcogarrisi@tutanota.com>"]
publish = false
edition = "2018"

[dependencies]
priority-queue = { path = ".." }
# no-std compatible hasher
twox-hash = { version = "1.5", default-features = false }

[dev-dependencies]